window.echosfallPresetNames = [
  "BC-0077 - Dunhuang - Cinnabar Fresco Pulse",
  "BC-0108 - Morandi - Clay Vessel Stillness",
  "BC-0114 - Zen - Single Stone Tide",
  "BC-0145 - Desert - Salt Dune Shadow",
  "BC-0156 - Dreamy - Cloud Staircase",
  "BC-0183 - Ceramic - Cobalt Kiln Bloom",
  "BC-0215 - Monet - Lilypad Broken Light",
  "BC-0248 - Nebula - Violet Dust Nursery",
  "BC-0263 - Iridescent - Moth Wing Silence",
  "BC-0291 - Morandi - Rose Concrete Facade",
  "BC-0312 - Abyss - Jellyfish Lantern Pulse",
  "BC-0365 - Glitch - Phosphor Scanline Memory",
  "BC-0377 - Monet - Steam Station at Blue Hour",
  "BC-0429 - Crystal - Ice Fracture Index",
  "BC-0442 - Psychedelic - Tangerine Mirage",
  "BC-0487 - Morandi - Dusty Eucalyptus Study",
  "BC-0518 - Still Life - Amber Bottle Shadow",
  "BC-0542 - Psychedelic - Oil Slick Cathedral",
  "BC-0579 - Monet - Rouen Haze Clock",
  "BC-0588 - Impasto - Vermilion Knife Ridge",
  "BC-0623 - Ink - Dragon Soot Ribbon",
  "BC-0654 - Cyber - Amber Terminal Rain",
  "BC-0692 - Moire - Brass Interference",
  "BC-0731 - Monet - Seine Copper Evening",
  "BC-0765 - Frost - Haystack at First Light",
  "BC-0814 - Kaleidoscope - Rose Window Fold",
  "BC-0881 - Aurora - Slow Green Curtain",
  "BC-0897 - Lotus - Moon Pool Rings",
  "BC-0902 - Fractal - Electric Pollen",
  "BC-0934 - Neon - Liquid Cassette Melt"
];
