window.echosfallPresetNames = [
  "FFVoid - Monolith Zenith",
  "FFVoid - Cyber Sanctum",
  "FFVoid - Obsidian Spire",
  "FFVoid - Hypercube Cathedral",
  "FFVoid - Chrono Monolith",
  "FFVoid - Celestial Bastion",
  "FFVoid - Solar Flare Temple",
  "FFVoid - Infinite Corridor",
  "FFVoid - Obsidian Mirror Maze",
  "FFVoid - Cyber Spire Array",
  "FFVoid - Crystalline Abyss",
  "FFVoid - Prism Gateway",
  "FFVoid - Emerald Labyrinth",
  "FFVoid - Diamond Helix",
  "FFVoid - Titanium Fractal",
  "FFVoid - Ruby Singularity",
  "FFVoid - Bismuth Palace",
  "FFVoid - Opaline Nebula",
  "FFVoid - Sapphire Core",
  "FFVoid - Amber Hive",
  "FFVoid - Quantum Tesseract",
  "FFVoid - Event Horizon Portal",
  "FFVoid - Cybernetic Torus",
  "FFVoid - Astral Lattice",
  "FFVoid - Zero Point Nexus",
  "FFVoid - Graviton Well",
  "FFVoid - Tachyon Conduit",
  "FFVoid - Dimensional Mirror",
  "FFVoid - Superstring Reactor",
  "FFVoid - Omega Horizon",
  "FFVoid - Bioluminescent Nexus",
  "FFVoid - Velvet Void Sphere",
  "FFVoid - Void Flower Bloom",
  "FFVoid - Neon Jellyfish Core",
  "FFVoid - Chitinous Hive",
  "FFVoid - Spore Cavern",
  "FFVoid - Plasma Nautilus",
  "FFVoid - Alien Chrysalis",
  "FFVoid - Coral Cosmos",
  "FFVoid - Bio-Matrix Heart",
  "FFVoid - Nebula Engine",
  "FFVoid - Dark Matter Forge",
  "FFVoid - Pulsar Citadel",
  "FFVoid - Supernova Pillar",
  "FFVoid - Holographic Pyramid",
  "FFVoid - Silicon Dreamscape",
  "FFVoid - Cosmic Loom",
  "FFVoid - Radiant Hexagon",
  "FFVoid - Starlight Obelisk",
  "FFVoid - Retrograde Galaxy"
];
